type: object
properties:
  operationType:
    type: string
    enum:
      - ADD
      - EDIT
      - REMOVE
  subject:
    $ref: ./Object.yaml
  previousState:
    $ref: ./Object.yaml
  involvedElements:
    $ref: ./ActionInvolvedElements.yaml
  subactions:
    type: array
    items:
      $ref: ./Action.yaml
  user:
    $ref: ./ActionUser.yaml
  timestamp:
    $ref: ./BigDecimal.yaml
