type: object
properties:
  format:
    type: string
  annotations:
    type: array
    items:
      type: string
  datasource:
    type: string
  ontologyIri:
    type: string
  ontologyVersion:
    type: string
