type: object
properties:
  themes:
    type: array
    items:
      $ref: ./Theme.yaml
  selectedTheme:
    type: string
  language:
    type: string
  entityNameType:
    type: string
    enum:
      - LABEL
      - PREFIXED_IRI
      - FULL_IRI
  renderers:
    type: array
    items:
      type: string
  widgets:
    $ref: ./Object.yaml
  filters:
    type: array
    items:
      type: string
      enum:
        - ALL
        - DATA_PROPERTY
        - VALUE_DOMAIN
        - INDIVIDUAL
        - UNIVERSAL_QUANTIFIER
        - COMPLEMENT
        - HAS_KEY
