openapi: 3.0.0
servers:
  - url: 'https://{tenant}/mws/rest/mwsx'
    variables:
      tenant:
        default: localhost
        description: Your localhost
info:
  description: >-
    This is the API for managing saved SPARQL queries in Mastro.
  version: 1.0.0
  title: Queries API model
  contact:
    email: info@obdasystems.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /owlOntology/{name}/version/querycatalog:
    $ref: paths/owlOntology_{name}_version_querycatalog.yaml
  /owlOntology/{name}/version/querycatalog/converted2sparqling:
    $ref: paths/owlOntology_{name}_version_querycatalog_converted2sparqling.yaml
  /owlOntology/{name}/version/query/{queryID}/publication:
    $ref: paths/owlOntology_{name}_version_query_{queryID}_publication.yaml
  /owlOntology/{name}/version/querycatalog/publicationRequests:
    $ref: paths/owlOntology_{name}_version_querycatalog_publicationRequests.yaml
  /owlOntology/{name}/version/querycatalog/{userCatalog}/query/{queryID}/publication:
    $ref: >-
      paths/owlOntology_{name}_version_querycatalog_{userCatalog}_query_{queryID}_publication.yaml
  /owlOntology/{name}/version/querycatalog/export:
    $ref: paths/owlOntology_{name}_version_querycatalog_export.yaml
  /owlOntology/{name}/version/querycatalog/import:
    $ref: paths/owlOntology_{name}_version_querycatalog_import.yaml
  /owlOntology/{name}/version/querycatalog/sparqling/import:
    $ref: paths/owlOntology_{name}_version_querycatalog_sparqling_import.yaml
  /owlOntology/{name}/version/querycatalog/sparqling/migrate:
    $ref: paths/owlOntology_{name}_version_querycatalog_sparqling_migrate.yaml
  /owlOntology/{name}/version/querycatalog/sparqling:
    $ref: paths/owlOntology_{name}_version_querycatalog_sparqling.yaml
  /owlOntology/{name}/version/querycatalog/sparqling/export:
    $ref: paths/owlOntology_{name}_version_querycatalog_sparqling_export.yaml
  /owlOntology/{name}/version/query/{ID}:
    $ref: paths/owlOntology_{name}_version_query_{ID}.yaml
  /owlOntology/{name}/version/query:
    $ref: paths/owlOntology_{name}_version_query.yaml
  /owlOntology/{name}/version/queries/sparqling:
    $ref: paths/owlOntology_{name}_version_queries_sparqling.yaml
  /owlOntology/{name}/version/query/sparqling/{ID}:
    $ref: paths/owlOntology_{name}_version_query_sparqling_{ID}.yaml
  /owlOntology/{name}/version/query/sparqling:
    $ref: paths/owlOntology_{name}_version_query_sparqling.yaml
components: 
  securitySchemes: 
    api-key: 
      $ref: './components/securitySchemes/api-key.yaml'
    jwt:
      $ref: './components/securitySchemes/jwt.yaml'
security: 
  - api-key: []
  - jwt: []