openapi: 3.0.0
servers:
  - url: 'https://{tenant}/mws/rest/mwsx'
    variables:
      tenant:
        default: localhost
        description: Your localhost
info:
  description: >-
    This is the API to transform the data of the ontology into RDF triples.
    The transformation is done by means of a set of mappings and a connection
    to a DBMS. 
  version: 1.0.0
  title: Triplify API model
  contact:
    email: info@obdasystems.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /triplify/start:
    $ref: paths/triplify_start.yaml
  /owlOntology/{name}/mappings/{mapID}/triplify/listThreads:
    $ref: paths/owlOntology_{name}_mappings_{mapID}_triplify_listThreads.yaml
  /owlOntology/{name}/mappings/{mapID}/triplify/listThreadProgresses:
    $ref: >-
      paths/owlOntology_{name}_mappings_{mapID}_triplify_listThreadProgresses.yaml
  /triplify/stopAll:
    $ref: paths/triplify_stopAll.yaml
  /triplify/{threadID}/stop:
    $ref: paths/triplify_{threadID}_stop.yaml
  /triplify/{threadID}:
    $ref: paths/triplify_{threadID}.yaml
  /triplify/{threadID}/status:
    $ref: paths/triplify_{threadID}_status.yaml
  /triplify/{threadID}/report:
    $ref: paths/triplify_{threadID}_report.yaml
  /triplify/{threadID}/download:
    $ref: paths/triplify_{threadID}_download.yaml
  /owlOntology/{name}/version/mapping/{mapID}/triplify/{datasource}:
    $ref: >-
      paths/owlOntology_{name}_version_mapping_{mapID}_triplify_{datasource}.yaml
components: 
  securitySchemes: 
    api-key: 
      $ref: './components/securitySchemes/api-key.yaml'
    jwt:
      $ref: './components/securitySchemes/jwt.yaml'
security: 
  - api-key: []
  - jwt: []