get:
  description: No description available for this method
  parameters: []
  consumes:
    - application/json
  produces:
    - application/json
  tags:
    - USERS AND ROLES
  responses:
    '200':
      description: OK
      schema:
        $ref: '#/definitions/com.mwsx.model.PermissionParameters'
    '401':
      description: The user does not have sufficient privileges to invoke this service
    '403':
      description: User not authorized due to wrong credentials
    '500':
      description: An internal server error occurred while performing the request
    '510':
      description: This method is currently not implemented
