title: ChartConfiguration
type: object
required:
  - yVariables
properties:
  yVariables:
    type: array
    items:
      type: string
  series:
    type: string
  xVariable:
    type: string
  chartType:
    type: string
  cutoff:
    type: integer
    format: int32
