title: RDFGraphConfig
type: object
properties:
  entityNameType:
    type: string
  themes:
    type: array
    items:
      $ref: ./Theme.yaml
  renderers:
    type: array
    items:
      type: string
  language:
    type: string
  filters:
    type: array
    items:
      type: string
  widgets:
    type: string
  selectedTheme:
    type: string
