swagger: '2.0'
info:
  title: MWS Mapping Triplification
  description: >-
    Mastro Web Services: RESTFul interface for mapping triplification
    functionality
  contact:
    name: Marco Ruzzi
    url: http://www.obdasystems.com
    email: marco.ruzzi@obdasystems.com
  version: 3.0.0
host: default-host
basePath: /base/path
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /triplify/{threadID}/stop:
    put:
      description: Stops the thread identified by threadID
      parameters:
        - name: threadID
          in: path
          required: true
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - MAPPING TRIPLIFICATION
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
  /triplify/{threadID}:
    delete:
      description: Stops the thread identified by threadID
      parameters:
        - name: threadID
          in: path
          required: true
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - MAPPING TRIPLIFICATION
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
  /triplify/{threadID}/report:
    get:
      description: Returns the report of a triplification thread
      parameters:
        - name: threadID
          in: path
          required: true
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - MAPPING TRIPLIFICATION
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/com.ruzzi.triplification.OBDATriplificationReport'
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
  /triplify/start:
    post:
      description: Starts a new thread of mappings triplification with the given parameters
      parameters:
        - name: arg2
          in: body
          required: false
          schema:
            $ref: '#/definitions/com.ruzzi.triplification.OBDATriplificationRequest'
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - MAPPING TRIPLIFICATION
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
  /owlOntology/{name}/mappings/{mapID}/triplify/listThreads:
    get:
      description: Lists the triplification threads for a given mapping specification
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: mapID
          in: path
          required: true
          type: string
        - name: version
          in: query
          required: false
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - MAPPING TRIPLIFICATION
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
  /triplify/{threadID}/status:
    get:
      description: Returns the status of a triplification thread
      parameters:
        - name: threadID
          in: path
          required: true
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - MAPPING TRIPLIFICATION
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/com.ruzzi.triplification.OBDATriplificationProgress'
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
  /owlOntology/{name}/mappings/{mapID}/triplify/listThreadProgresses:
    get:
      description: Lists the triplification threads for a given mapping specification
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: mapID
          in: path
          required: true
          type: string
        - name: version
          in: query
          required: false
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - MAPPING TRIPLIFICATION
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: >-
                #/definitions/com.ruzzi.triplification.OBDATriplificationProgress
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
  /triplify/stopAll:
    put:
      description: Stops the thread identified by threadID
      parameters: []
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - MAPPING TRIPLIFICATION
      responses:
        '200':
          description: OK
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
  /triplify/{threadID}/download:
    get:
      description: Returns the report of a triplification thread
      parameters:
        - name: threadID
          in: path
          required: true
          type: string
      consumes:
        - application/json
      produces:
        - application/octet-stream
      tags:
        - MAPPING TRIPLIFICATION
      responses:
        '200':
          description: OK
          schema:
            type: file
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
definitions:
  com.ruzzi.triplification.OBDATriplificationProgress:
    title: com.ruzzi.triplification.OBDATriplificationProgress
    type: object
    properties:
      threadId:
        type: string
      progress:
        type: integer
        format: int32
      startTime:
        type: integer
        format: int64
      time:
        type: integer
        format: int64
      status:
        type: string
  com.ruzzi.triplification.OBDATriplificationReport:
    title: com.ruzzi.triplification.OBDATriplificationReport
    type: object
    properties:
      request:
        $ref: '#/definitions/com.ruzzi.triplification.OBDATriplificationRequest'
      progress:
        $ref: '#/definitions/com.ruzzi.triplification.OBDATriplificationProgress'
      details:
        type: object
        additionalProperties:
          $ref: >-
            #/definitions/com.ruzzi.triplification.OBDATriplificationMappingReport
  com.ruzzi.triplification.OBDATriplificationMappingReport:
    title: com.ruzzi.triplification.OBDATriplificationMappingReport
    type: object
    properties:
      entityIRI:
        type: string
      triplesCount:
        type: integer
        format: int32
      sqlCode:
        type: string
      startTime:
        type: integer
        format: int64
      endTime:
        type: integer
        format: int64
      error:
        type: string
      elapsedTime:
        type: integer
        format: int64
  com.ruzzi.triplification.OBDATriplificationRequest:
    title: com.ruzzi.triplification.OBDATriplificationRequest
    type: object
    properties:
      mappingID:
        type: string
      entityIriFilter:
        type: array
        items:
          type: string
      ontologyVersion:
        type: string
      ontologyName:
        type: string
      mappingIdFilter:
        type: array
        items:
          type: string
      outputRdfFormat:
        type: string
      dataSource:
        type: string
