get:
  tags: [Roles]
  summary: GET mwsx/role/configurations
  operationId: get__role_configs
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema: {$ref: ../components/schemas/PermissionParameters.yaml}
    '401': {description: Unhauthorized}
