openapi: 3.0.0
servers:
  - url: '{protocol}://{tenant}{port}'
    variables:
      protocol:
        default: https
      tenant:
        default: localhost
      port: 
        default: ':8080'
info:
  description: >-
    This is the API for the AI assistant module
  version: 1.0.0
  title: AI assistant API model
  contact:
    email: info@obdasystems.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /ontologyDraft/ai/{name}:
    $ref: paths/ontologyDraft_ai_{name}.yaml
  /ai/entity_description:
    $ref: paths/ai_entity_description.yaml
  /ai/individual_description:
    $ref: paths/ai_individual_description.yaml
  /ai/class_data_properties:
    $ref: paths/ai_class_data_properties.yaml
  /ai/class_subclasses:
    $ref: paths/ai_class_subclasses.yaml
  /ai/sparql_description:
    $ref: paths/ai_sparql_description.yaml
components: 
  securitySchemes: 
    jwt:
      $ref: './components/securitySchemes/jwt.yaml'
security: 
  - jwt: []