openapi: 3.0.0
servers:
  - url: "{protocol}://{tenant}{port}"
    variables:
      protocol:
        default: https
      tenant:
        default: localhost
      port:
        default: ":8080"
info:
  description: >-
    This is the API for the AI assistant module
  version: 1.0.0
  title: AI assistant API model
  contact:
    email: info@obdasystems.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /ai/entity_description:
    $ref: paths/ai_entity_description.yaml
  /ai/individual_description:
    $ref: paths/ai_individual_description.yaml
  /ai/class_data_properties:
    $ref: paths/ai_class_data_properties.yaml
  /ai/class_subclasses:
    $ref: paths/ai_class_subclasses.yaml
  /ai/sparql_description:
    $ref: paths/ai_sparql_description.yaml
  /ai/autochart:
    $ref: paths/ai_autochart.yaml
  /ai/autochart_description:
    $ref: paths/ai_autochart_description.yaml
  /ai/text2sparql:
    $ref: paths/ai_text2sparql.yaml
  /ai/rag/ontologyDraft/{name}:
    $ref: paths/ai_rag_ontologyDraft_name.yaml
  /ai/rag/{ontologyName}/vectorDB/initialize:
    $ref: paths/ai_rag_ontologyName_vectorDB_initialize.yaml
  /ai/rag/{ontologyName}/vectorDB/status:
    $ref: paths/ai_rag_ontologyName_vectorDB_status.yaml
  /ai/rag/{ontologyName}/vectorDB/delete:
    $ref: paths/ai_rag_ontologyName_vectorDB_delete.yaml
  /ai/rag/{ontologyName}/vectorDB/nlq:
    $ref: paths/ai_rag_ontologyName_vectorDB_nlq.yaml
  /ai/ontologyDraft/download:
    $ref: paths/ai_ontologyDraft_download.yaml
  /ai/ontologyDraft/convertOWL:
    $ref: paths/ai_ontologyDraft_convertOWL.yaml
components:
  schemas:
    OntologyEntity:
      $ref: ./components/schemas/OntologyEntity.yaml
  securitySchemes:
    jwt:
      $ref: "./components/securitySchemes/jwt.yaml"
security:
  - jwt: []
