openapi: 3.0.0
servers:
  - url: 'https://{tenant}/mws/rest/mwsx'
    variables:
      tenant:
        default: localhost
        description: Your localhost
info:
  description: >-
    This is the API for manage Authorization View Proviles (AVPs) 
    used in Mastro to restrict the access to the data by means of 
    filtering some of the entities of the ontologies. This entity
    sets are builded using the Mastro reasoner and are used in the 
    definition of endpoints which will have restricted access. 
  version: 1.0.0
  title: AVPs API model
  contact:
    email: info@obdasystems.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /owlOntology/{name}/version/avpOntologyTree:
    $ref: paths/owlOntology_{name}_version_avpOntologyTree.yaml
  /owlOntology/{name}/version/authorizationViewProfiles:
    $ref: paths/owlOntology_{name}_version_authorizationViewProfiles.yaml
  /owlOntology/{name}/version/authorizationViewProfile/{avpId}:
    $ref: paths/owlOntology_{name}_version_authorizationViewProfile_{avpId}.yaml
components: 
  securitySchemes: 
    api-key: 
      $ref: './components/securitySchemes/api-key.yaml'
    jwt:
      $ref: './components/securitySchemes/jwt.yaml'
security: 
  - api-key: []
  - jwt: []