openapi: 3.0.0
servers:
  - url: '{protocol}://{tenant}{port}/mws/rest/mwsx'
    variables:
      protocol:
        default: https
      tenant:
        default: localhost
      port:
        default: ':8989'
info:
  description: >-
    This is the API for Data Quality in Mastro. It generates queries
    and execute them in order to verify if the underlying data in the DBMS
    is consistent with the ontology.
  version: 1.0.0
  title: Data Quality API model
  contact:
    email: info@obdasystems.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /owlOntology/{name}/version/ontologyConstraints:
    $ref: paths/owlOntology_{name}_version_ontologyConstraints.yaml
  /owlOntology/{name}/version/shaclConstraints:
    $ref: paths/owlOntology_{name}_version_shaclConstraints.yaml
  /owlOntology/{name}/version/ontologyConstraints/set:
    $ref: paths/owlOntology_{name}_version_ontologyConstraints_set.yaml
  /owlOntology/{name}/version/ontologyConstraints/set/{setId}:
    $ref: paths/owlOntology_{name}_version_ontologyConstraints_set_{setId}.yaml
  /owlOntology/{name}/version/ontologyConstraints/set/{setId}/start/{endpoint}:
    $ref: >-
      paths/owlOntology_{name}_version_ontologyConstraints_set_{setId}_start_{endpoint}.yaml
  /owlOntology/{name}/version/ontologyConstraints/set/{setId}/stop:
    $ref: paths/owlOntology_{name}_version_ontologyConstraints_set_{setId}_stop.yaml
  /owlOntology/{name}/version/ontologyConstraints/set/{setId}/removeThread:
    $ref: >-
      paths/owlOntology_{name}_version_ontologyConstraints_set_{setId}_removeThread.yaml
  /owlOntology/{name}/version/ontologyConstraints/set/{setId}/status:
    $ref: >-
      paths/owlOntology_{name}_version_ontologyConstraints_set_{setId}_status.yaml
  /owlOntology/{name}/version/ontologyConstraints/sets/running:
    $ref: paths/owlOntology_{name}_version_ontologyConstraints_sets_running.yaml
  /owlOntology/{name}/version/ontologyConstraints/sets/executionLogs:
    $ref: >-
      paths/owlOntology_{name}_version_ontologyConstraints_sets_executionLogs.yaml
  /owlOntology/{name}/version/ontologyConstraints/set/{setId}/executionLog:
    $ref: >-
      paths/owlOntology_{name}_version_ontologyConstraints_set_{setId}_executionLog.yaml
  /owlOntology/{name}/version/ontologyConstraints/set/{setId}/executionLogs/timestamps:
    $ref: >-
      paths/owlOntology_{name}_version_ontologyConstraints_set_{setId}_executionLogs_timestamps.yaml
  /owlOntology/{name}/version/ontologyConstraints/set/{setId}/executionLogs/timestamp/{timestamp}:
    $ref: >-
      paths/owlOntology_{name}_version_ontologyConstraints_set_{setId}_executionLogs_timestamp_{timestamp}.yaml
  /owlOntology/{name}/version/ontologyConstraints/set/{setId}/executionLog/timestamps:
    $ref: >-
      paths/owlOntology_{name}_version_ontologyConstraints_set_{setId}_executionLog_timestamps.yaml
  /owlOntology/{name}/version/ontologyConstraints/set/{setId}/dump:
    $ref: paths/owlOntology_{name}_version_ontologyConstraints_set_{setId}_dump.yaml
  /owlOntology/{name}/version/ontologyConstraints/sets/dump:
    $ref: paths/owlOntology_{name}_version_ontologyConstraints_sets_dump.yaml
components: 
  securitySchemes: 
    apiKey: 
      $ref: './components/securitySchemes/api-key.yaml'
    jwt:
      $ref: './components/securitySchemes/jwt.yaml'
security: 
  - apiKey: []
  - jwt: []
