openapi: 3.0.0
servers:
  - url: '{protocol}://{tenant}{port}/mws/rest/mwsx'
    variables:
      protocol:
        default: https
      tenant:
        default: localhost
      port:
        default: ':8989'
info:
  description: >-
    This is the API for managing Knowledge Graphs in Mastro.
    Knowledge Graphs are RDF materializations powered by RDF4J.
  version: 1.0.0
  title: Grapholscape API model
  contact:
    email: info@obdasystems.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /knowledgeGraphs:
    $ref: paths/knowledgeGraphs.yaml
  /knowledgeGraph:
    $ref: paths/knowledgeGraph.yaml
  /knowledgeGraph/info:
    $ref: paths/knowledgeGraph_info.yaml
  /knowledgeGraph/prefixes:
    $ref: paths/knowledgeGraph_prefixes.yaml
  /knowledgeGraph/folder:
    $ref: paths/knowledgeGraph_folder.yaml
  /knowledgeGraph/status:
    $ref: paths/knowledgeGraph_status.yaml
  /knowledgeGraph/status/list:
    $ref: paths/knowledgeGraph_status_list.yaml
  /lastLoaded/knowledgeGraph:
    $ref: paths/lastLoaded_knowledgeGraph.yaml
  /knowledgeGraph/file:
    $ref: paths/knowledgeGraph_file.yaml
  /knowledgeGraph/classes:
    $ref: paths/knowledgeGraph_classes.yaml
  /knowledgeGraph/classes/stats:
    $ref: paths/knowledgeGraph_classes_stats.yaml
  /knowledgeGraph/class/instances:
    $ref: paths/knowledgeGraph_class_instances.yaml
  /knowledgeGraph/namedGraphs:
    $ref: paths/knowledgeGraph_namedGraphs.yaml
  /knowledgeGraph/instances:
    $ref: paths/knowledgeGraph_instances.yaml
  /knowledgeGraph/union:
    $ref: paths/knowledgeGraph_union.yaml
  /knowledgeGraph/union/ontology:
    $ref: paths/knowledgeGraph_union_ontology.yaml
  /knowledgeGraph/union/queryKg:
    $ref: paths/knowledgeGraph_union_queryKg.yaml
  /knowledgeGraph/query/catalog:
    $ref: paths/knowledgeGraph_query_catalog.yaml
  /knowledgeGraph/query/catalog/export:
    $ref: paths/knowledgeGraph_query_catalog_export.yaml
  /knowledgeGraph/query/catalog/{queryID}:
    $ref: paths/knowledgeGraph_query_catalog_{queryID}.yaml
  /knowledgeGraph/query/start:
    $ref: paths/knowledgeGraph_query_start.yaml
  /knowledgeGraph/query/catalog/{queryID}/start:
    $ref: paths/knowledgeGraph_query_catalog_{queryID}_start.yaml
  /knowledgeGraph/query/{queryID}/stop:
    $ref: paths/knowledgeGraph_query_{queryID}_stop.yaml
  /knowledgeGraph/query/{queryID}/exportResults:
    $ref: paths/knowledgeGraph_query_{queryID}_exportResults.yaml
  /knowledgeGraph/query/{queryID}/status:
    $ref: paths/knowledgeGraph_query_{queryID}_status.yaml
  /knowledgeGraph/query/{queryId}:
    $ref: paths/knowledgeGraph_query_{queryId}.yaml
  /knowledgeGraph/query/{queryID}/results:
    $ref: paths/knowledgeGraph_query_{queryID}_results.yaml
  /knowledgeGraph/instance/page:
    $ref: paths/knowledgeGraph_instance_page.yaml
  /knowledgeGraph/instance/objectType:
    $ref: paths/knowledgeGraph_instance_objectType.yaml
  /knowledgeGraph/instance/subjectType:
    $ref: paths/knowledgeGraph_instance_subjectType.yaml
  /knowledgeGraph/store/file:
    $ref: paths/knowledgeGraph_store_file.yaml
  /knowledgeGraph/store/file/{name}:
    $ref: paths/knowledgeGraph_store_file_{name}.yaml
  /knowledgeGraph/upload/file:
    $ref: paths/knowledgeGraph_upload_file.yaml
  /knowledgeGraph/upload/import:
    $ref: paths/knowledgeGraph_upload_import.yaml
  /knowledgeGraph/delete/file:
    $ref: paths/knowledgeGraph_delete_file.yaml
  /knowledgeGraph/delete/file/triples:
    $ref: paths/knowledgeGraph_delete_file_triples.yaml
  /knowledgeGraph/upload/remove:
    $ref: paths/knowledgeGraph_upload_remove.yaml
  /knowledgeGraph/upload/files:
    $ref: paths/knowledgeGraph_upload_files.yaml
  /knowledgeGraph/union/queryOBDA:
    $ref: paths/knowledgeGraph_union_queryOBDA.yaml
  /knowledgeGraph/upload/file/csv:
    $ref: paths/knowledgeGraph_upload_file_csv.yaml
  /knowledgeGraph/upload/files/csv:
    $ref: paths/knowledgeGraph_upload_files_csv.yaml
  /knowledgeGraph/delete/file/csv/{fileName}:
    $ref: paths/knowledgeGraph_delete_file_csv_{fileName}.yaml
  /knowledgeGraph/file/csv/{fileName}/preview:
    $ref: paths/knowledgeGraph_file_csv_{fileName}_preview.yaml
  /knowledgeGraph/upload/import/csv:
    $ref: paths/knowledgeGraph_upload_import_csv.yaml
  /knowledgeGraph/upload/import/threads:
    $ref: paths/knowledgeGraph_upload_import_threads.yaml
  /knowledgeGraph/upload/import/thread:
    $ref: paths/knowledgeGraph_upload_import_thread.yaml
components: 
  securitySchemes: 
    apiKey: 
      $ref: './components/securitySchemes/api-key.yaml'
    jwt:
      $ref: './components/securitySchemes/jwt.yaml'
security: 
  - apiKey: []
  - jwt: []