openapi: 3.0.0
servers:
  - url: '{protocol}://{tenant}{port}/mws/rest/mwsx'
    variables:
      protocol:
        default: https
      tenant:
        default: localhost
      port:
        default: ':8989'
info:
  description: This is the API for managing the Ontology Catalog
  version: 1.0.0
  title: Ontology Catalog API model
  contact:
    email: info@obdasystems.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /ontologyCatalog:
    $ref: paths/ontologyCatalog.yaml
  /ontologyCatalog/query/start:
    $ref: paths/ontologyCatalog_query_start.yaml
  /ontologyCatalog/query/{queryID}/stop:
    $ref: paths/ontologyCatalog_query_{queryID}_stop.yaml
  /ontologyCatalog/query/{queryID}/status:
    $ref: paths/ontologyCatalog_query_{queryID}_status.yaml
  /ontologyCatalog/query/{queryID}/results:
    $ref: paths/ontologyCatalog_query_{queryID}_results.yaml
components: 
  securitySchemes: 
    apiKey: 
      $ref: './components/securitySchemes/api-key.yaml'
    jwt:
      $ref: './components/securitySchemes/jwt.yaml'
security: 
  - apiKey: []
  - jwt: []