openapi: 3.0.0
servers:
  - url: '{protocol}://{tenant}{port}/mws/rest/mwsx'
    variables:
      protocol:
        default: https
      tenant:
        default: localhost
      port:
        default: ':8989'
info:
  description: >-
    This is the API for retaining a Grapholscape's loaded ontology (or graph) in
    order to restart navigation from a previous state.
  version: 1.0.0
  title: Ontology Designer API model
  contact:
    email: info@obdasystems.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /ontologyDraftInfos:
    $ref: paths/ontologyDraftInfos.yaml
  /ontologyDraft/{ontologyName}:
    $ref: paths/ontologyDraft_{ontologyName}.yaml
  /ontologyDraft/download:
    $ref: paths/ontologyDraft_download.yaml
components: 
  securitySchemes: 
    apiKey: 
      $ref: './components/securitySchemes/api-key.yaml'
    jwt:
      $ref: './components/securitySchemes/jwt.yaml'
security: 
  - apiKey: []
  - jwt: []