openapi: 3.0.1
servers:
  - url: '{protocol}://{tenant}{port}/mws/rest/mwsx'
    variables:
      protocol:
        default: https
      tenant:
        default: localhost
      port:
        default: ':8989'
info:
  title: Sparqling API model
  description: >-
    This server will expose an API to Sparqling front end to create new SPARQL
    queries with a combinations of point and click on the
    [GRAPHOLscape](https://github.com/obdasystems/grapholscape) graph.
  termsOfService: http://swagger.io/terms/
  contact:
    email: info@obdasystems.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.1.0
tags:
  - name: OntologyGraph
    description: >-
      Depending on the selected node and the clicked node the ontology graph
      will change the highlightments. These results will be used essentially by
      GRAPHOLscape.
  - name: QueryGraphBGP
    description: >-
      Depending on the selected node and the clicked node the server will
      compute the query graph which will be rendered by Sparqling front end.
      These result will be used to render the query graph and the query head and
      the SPARQL code. These operations will modify only the basic graph
      pattern.
  - name: QueryGraphHead
    description: These operations will modify the query graph head.
  - name: QueryGraphFilter
    description: These operations will modify the query graph filter part.
  - name: QueryGraphOptional
    description: These operations will modify the query graph optional part.
  - name: QueryGraphExtra
    description: These are extra operations for the query graph.
  - name: VisualizeSPARQL
    description: >-
      These operations will translate a SPARQL query in a query graph to be
      visualized and modified in Sparqling
paths:
  /owlOntology/{ontologyName}/highlights:
    $ref: paths/owlOntology_{ontologyName}_highlights.yaml
  /owlOntology/{ontologyName}/highlights/paths:
    $ref: paths/owlOntology_{ontologyName}_highlights_paths.yaml
  /owlOntology/{name}/highlights/paths/thread/start:
    $ref: paths/owlOntology_{name}_highlights_paths_thread_start.yaml
  /owlOntology/{name}/highlights/paths/thread/stop:
    $ref: paths/owlOntology_{name}_highlights_paths_thread_stop.yaml
  /owlOntology/{name}/highlights/paths/thread/result:
    $ref: paths/owlOntology_{name}_highlights_paths_thread_result.yaml
  /owlOntology/{name}/highlights/paths/thread/state:
    $ref: paths/owlOntology_{name}_highlights_paths_thread_state.yaml
  /owlOntology/{name}/highlights/paths/thread/error:
      $ref: paths/owlOntology_{name}_highlights_paths_thread_error.yaml
  /owlOntology/{ontologyName}/queryGraph/node:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_node.yaml
  /owlOntology/{ontologyName}/queryGraph/node/class/{graphElementId}:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_class_{graphElementId}.yaml
  /owlOntology/{ontologyName}/queryGraph/node/objectProperty/{graphElementId}:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_objectProperty_{graphElementId}.yaml
  /owlOntology/{ontologyName}/queryGraph/node/dataProperty/{graphElementId}:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_dataProperty_{graphElementId}.yaml
  /owlOntology/{ontologyName}/queryGraph/node/annotation/{graphElementId}:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_annotation_{graphElementId}.yaml
  ? /owlOntology/{ontologyName}/queryGraph/node/join/{graphElementId1}/{graphElementId2}
  : $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_join_{graphElementId1}_{graphElementId2}.yaml
  /owlOntology/{ontologyName}/queryGraph/node/delete/{graphElementId}:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_delete_{graphElementId}.yaml
  /owlOntology/{ontologyName}/queryGraph/node/delete/{graphElementId}/class:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_delete_{graphElementId}_class.yaml
  /owlOntology/{ontologyName}/queryGraph/node/filter/{filterId}:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_node_filter_{filterId}.yaml
  /owlOntology/{ontologyName}/queryGraph/node/filter/edit/{filterId}:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_filter_edit_{filterId}.yaml
  /owlOntology/{ontologyName}/queryGraph/node/filter/remove/{filterId}:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_filter_remove_{filterId}.yaml
  /owlOntology/{ontologyName}/queryGraph/node/filter/remove/all:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_node_filter_remove_all.yaml
  /owlOntology/{ontologyName}/queryGraph/node/optional/{graphElementId}:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_optional_{graphElementId}.yaml
  /owlOntology/{ontologyName}/queryGraph/node/optional/remove/{graphElementId}:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_node_optional_remove_{graphElementId}.yaml
  /owlOntology/{ontologyName}/queryGraph/node/optional/remove/all:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_node_optional_remove_all.yaml
  /owlOntology/{ontologyName}/queryGraph/head/add/{graphElementId}:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_head_add_{graphElementId}.yaml
  /owlOntology/{ontologyName}/queryGraph/head/delete/{headTerm}:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_head_delete_{headTerm}.yaml
  /owlOntology/{ontologyName}/queryGraph/head/rename/{headTerm}:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_head_rename_{headTerm}.yaml
  /owlOntology/{ontologyName}/queryGraph/head/orderBy/{headTerm}:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_head_orderBy_{headTerm}.yaml
  /owlOntology/{ontologyName}/queryGraph/head/function/{headTerm}:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_head_function_{headTerm}.yaml
  /owlOntology/{ontologyName}/queryGraph/head/aggregation/{headTerm}:
    $ref: >-
      paths/owlOntology_{ontologyName}_queryGraph_head_aggregation_{headTerm}.yaml
  /owlOntology/{ontologyName}/queryGraph/head/reorderHeadTerms:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_head_reorderHeadTerms.yaml
  /owlOntology/{ontologyName}/queryGraph/distinct:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_distinct.yaml
  /owlOntology/{ontologyName}/queryGraph/countStar/{active}:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_countStar_{active}.yaml
  /owlOntology/{ontologyName}/queryGraph/limit:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_limit.yaml
  /owlOntology/{ontologyName}/queryGraph/offset:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_offset.yaml
  /owlOntology/{ontologyName}/queryGraph/path/{graphElementId}:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_path_{graphElementId}.yaml
  /owlOntology/{ontologyName}/instanceShortestPath:
    $ref: paths/owlOntology_{ontologyName}_instanceShortestPath.yaml
  /owlOntology/{ontologyName}/constructify:
    $ref: paths/owlOntology_{ontologyName}_constructify.yaml
  /owlOntology/{ontologyName}/queryGraph/visualize:
    $ref: paths/owlOntology_{ontologyName}_queryGraph_visualize.yaml
  # /endpoint/{endpointName}/highligthsSharedViewsProps:
  #   $ref: paths/endpoint_{endpointName}_highligthsSharedViewsProps.yaml
  # /endpoint/{endpointName}/instanceShortestPath:
  #   $ref: paths/endpoint_{endpointName}_instanceShortestPath.yaml
components: 
  securitySchemes: 
    apiKey: 
      $ref: './components/securitySchemes/api-key.yaml'
    jwt:
      $ref: './components/securitySchemes/jwt.yaml'
security: 
  - apiKey: []
  - jwt: []