swagger: '2.0'
info:
  title: Mastro Web Services (MWS)
  description: 'Mastro Web Services: authorization view profiles related routes'
  contact:
    name: Marco Ruzzi
    url: http://www.obdasystems.com
    email: marco.ruzzi@obdasystems.com
  version: 3.0.0
host: default-host
basePath: /base/path
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /owlOntology/{name}/version/authorizationViewProfiles:
    get:
      description: No description available for this method
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: version
          in: query
          required: false
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - AUTHORIZATION VIEW PROFILES
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/com.mwsx.model.AuthorizationViewProfileInfo'
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
    post:
      description: No description available for this method
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: version
          in: query
          required: false
          type: string
        - name: arg4
          in: body
          required: false
          schema:
            $ref: '#/definitions/com.mwsx.model.AuthorizationViewProfileInfo'
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - AUTHORIZATION VIEW PROFILES
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/com.mwsx.model.AuthorizationViewProfileInfo'
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
  /owlOntology/{name}/version/avpOntologyTree:
    get:
      description: No description available for this method
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: version
          in: query
          required: false
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - AUTHORIZATION VIEW PROFILES
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/com.mwsx.model.avp.AvpOntologyTree'
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
  /owlOntology/{name}/version/authorizationViewProfile/{avpId}:
    put:
      description: No description available for this method
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: avpId
          in: path
          required: true
          type: string
        - name: version
          in: query
          required: false
          type: string
        - name: arg5
          in: body
          required: false
          schema:
            $ref: '#/definitions/com.mwsx.model.AuthorizationViewProfileInfo'
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - AUTHORIZATION VIEW PROFILES
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/com.mwsx.model.AuthorizationViewProfileInfo'
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
    delete:
      description: No description available for this method
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: avpId
          in: path
          required: true
          type: string
        - name: version
          in: query
          required: false
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - AUTHORIZATION VIEW PROFILES
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/com.mwsx.model.AuthorizationViewProfileInfo'
        '401':
          description: The user does not have sufficient privileges to invoke this service
        '403':
          description: User not authorized due to wrong credentials
        '500':
          description: An internal server error occurred while performing the request
        '510':
          description: This method is currently not implemented
definitions:
  it.uniroma1.dis.mastro.api.avp.AuthorizationViewProfile:
    title: it.uniroma1.dis.mastro.api.avp.AuthorizationViewProfile
    type: object
    properties:
      dataProperties:
        type: array
        items:
          type: string
      classes:
        type: array
        items:
          type: string
      objectProperties:
        type: array
        items:
          type: string
      id:
        type: string
  com.mwsx.model.avp.AvpTree:
    title: com.mwsx.model.avp.AvpTree
    type: object
    properties:
      objectPropertyTree:
        $ref: '#/definitions/com.mwsx.model.avp.AvpTreeNode'
      classTree:
        $ref: '#/definitions/com.mwsx.model.avp.AvpTreeNode'
      dataPropertyTree:
        $ref: '#/definitions/com.mwsx.model.avp.AvpTreeNode'
  com.mwsx.model.AuthorizationViewProfileInfo:
    title: com.mwsx.model.AuthorizationViewProfileInfo
    type: object
    properties:
      mappingId:
        type: string
      ontologyVersion:
        type: string
      profile:
        $ref: '#/definitions/it.uniroma1.dis.mastro.api.avp.AuthorizationViewProfile'
      ontologyName:
        type: string
      description:
        type: string
  com.mwsx.model.avp.AvpTreeNode:
    title: com.mwsx.model.avp.AvpTreeNode
    type: object
    properties:
      children:
        type: array
        items:
          $ref: '#/definitions/com.mwsx.model.avp.AvpTreeNode'
      entities:
        type: array
        items:
          $ref: '#/definitions/com.mwsx.model.Entity'
  com.mwsx.model.Entity:
    title: com.mwsx.model.Entity
    type: object
    properties:
      entityLabels:
        type: array
        items:
          $ref: '#/definitions/com.mwsx.model.Label'
      isDeprecated:
        type: boolean
      entityIRI:
        type: string
      entityType:
        type: string
      entityPrefixIRI:
        type: string
      entityRemainder:
        type: string
      entityID:
        type: string
  com.mwsx.model.avp.AvpOntologyTree:
    title: com.mwsx.model.avp.AvpOntologyTree
    type: object
    properties:
      avpTree:
        $ref: '#/definitions/com.mwsx.model.avp.AvpTree'
  com.mwsx.model.Label:
    title: com.mwsx.model.Label
    type: object
    properties:
      lang:
        type: string
      content:
        type: string
